// Catálogo de ciudades para autocompletado de lugares de viaje.
// Las mexicanas van sin sufijo; las internacionales llevan ", XX" (código de país)
// para distinguirlas a simple vista. El campo es texto libre: si una ciudad no
// está aquí, igual se puede escribir manualmente y se guarda tal cual.
export const CIUDADES: string[] = [
  // ── México ──────────────────────────────────────────────
  "Acapulco",
  "Acuña",
  "Aguascalientes",
  "Altamira",
  "Apodaca",
  "Bahía de Banderas",
  "Caborca",
  "Cabo San Lucas",
  "Campeche",
  "Cancún",
  "Cárdenas",
  "Celaya",
  "Chetumal",
  "Chihuahua",
  "Chilpancingo",
  "Ciudad Constitución",
  "Ciudad de México",
  "Ciudad del Carmen",
  "Ciudad Juárez",
  "Ciudad Obregón",
  "Ciudad Valles",
  "Ciudad Victoria",
  "Coatzacoalcos",
  "Colima",
  "Comitán",
  "Córdoba",
  "Cozumel",
  "Cuauhtémoc",
  "Cuautla",
  "Cuernavaca",
  "Culiacán",
  "Delicias",
  "Durango",
  "Ecatepec",
  "Ensenada",
  "Escobedo",
  "Fresnillo",
  "Gómez Palacio",
  "Guadalajara",
  "Guadalupe",
  "Guanajuato",
  "Guasave",
  "Guaymas",
  "Hermosillo",
  "Hidalgo del Parral",
  "Irapuato",
  "Juchitán",
  "La Paz",
  "Lagos de Moreno",
  "Lázaro Cárdenas",
  "León",
  "Lerdo",
  "Linares",
  "Loreto",
  "Los Cabos",
  "Los Mochis",
  "Manzanillo",
  "Matamoros",
  "Matehuala",
  "Mazatlán",
  "Mérida",
  "Mexicali",
  "Minatitlán",
  "Monclova",
  "Monterrey",
  "Morelia",
  "Navojoa",
  "Navolato",
  "Nezahualcóyotl",
  "Nogales",
  "Nuevo Casas Grandes",
  "Nuevo Laredo",
  "Oaxaca",
  "Orizaba",
  "Pachuca",
  "Piedras Negras",
  "Playa del Carmen",
  "Poza Rica",
  "Progreso",
  "Puebla",
  "Puerto Vallarta",
  "Querétaro",
  "Reynosa",
  "Rosarito",
  "Sabinas",
  "Salamanca",
  "Salina Cruz",
  "Saltillo",
  "San Cristóbal de las Casas",
  "San José del Cabo",
  "San Juan del Río",
  "San Luis Potosí",
  "San Luis Río Colorado",
  "San Miguel de Allende",
  "San Nicolás de los Garza",
  "San Pedro Garza García",
  "Santa Catarina",
  "Silao",
  "Tampico",
  "Tapachula",
  "Taxco",
  "Tecate",
  "Tecomán",
  "Tehuacán",
  "Tepic",
  "Texcoco",
  "Tijuana",
  "Tlalnepantla",
  "Tlaquepaque",
  "Tlaxcala",
  "Toluca",
  "Tonalá",
  "Torreón",
  "Tula",
  "Tulancingo",
  "Tulum",
  "Tuxtla Gutiérrez",
  "Tuxpan",
  "Uruapan",
  "Valladolid",
  "Veracruz",
  "Villahermosa",
  "Xalapa",
  "Zacatecas",
  "Zamora",
  "Zapopan",
  "Zihuatanejo",

  // ── Estados Unidos ──────────────────────────────────────
  "Nogales, US",
  "Tucson, US",
  "Phoenix, US",
  "Yuma, US",
  "Calexico, US",
  "San Diego, US",
  "El Paso, US",
  "Laredo, US",
  "McAllen, US",
  "Pharr, US",
  "Hidalgo, US",
  "Brownsville, US",
  "Los Angeles, US",
  "Long Beach, US",
  "San Francisco, US",
  "Oakland, US",
  "Sacramento, US",
  "Fresno, US",
  "Bakersfield, US",
  "San Jose, US",
  "Las Vegas, US",
  "Reno, US",
  "Salt Lake City, US",
  "Denver, US",
  "Albuquerque, US",
  "Boise, US",
  "Spokane, US",
  "San Antonio, US",
  "Austin, US",
  "Houston, US",
  "Dallas, US",
  "Fort Worth, US",
  "Oklahoma City, US",
  "Tulsa, US",
  "Wichita, US",
  "Kansas City, US",
  "Omaha, US",
  "Des Moines, US",
  "Minneapolis, US",
  "Chicago, US",
  "Milwaukee, US",
  "Indianapolis, US",
  "Detroit, US",
  "Columbus, US",
  "Cleveland, US",
  "Cincinnati, US",
  "St. Louis, US",
  "Louisville, US",
  "Nashville, US",
  "Memphis, US",
  "Little Rock, US",
  "New Orleans, US",
  "Baton Rouge, US",
  "Jackson, US",
  "Birmingham, US",
  "Atlanta, US",
  "Savannah, US",
  "Charleston, US",
  "Jacksonville, US",
  "Orlando, US",
  "Tampa, US",
  "Miami, US",
  "Fort Lauderdale, US",
  "West Palm Beach, US",
  "Charlotte, US",
  "Raleigh, US",
  "Richmond, US",
  "Washington, US",
  "Baltimore, US",
  "Philadelphia, US",
  "New York, US",
  "Newark, US",
  "Boston, US",
  "Buffalo, US",
  "Pittsburgh, US",
  "Norfolk, US",
  "Seattle, US",
  "Tacoma, US",
  "Portland, US",

  // ── Canadá ──────────────────────────────────────────────
  "Toronto, CA",
  "Montreal, CA",
  "Vancouver, CA",
  "Calgary, CA",
  "Edmonton, CA",
  "Ottawa, CA",
  "Winnipeg, CA",
  "Quebec City, CA",
  "Hamilton, CA",
  "Mississauga, CA",
  "Surrey, CA",
  "Windsor, CA",
  "Halifax, CA",
  "Saskatoon, CA",
  "Victoria, CA",

  // ── Guatemala ───────────────────────────────────────────
  "Ciudad de Guatemala, GT",
  "Quetzaltenango, GT",
  "Escuintla, GT",

  // ── Belice ──────────────────────────────────────────────
  "Belize City, BZ",
  "Belmopán, BZ",

  // ── El Salvador ─────────────────────────────────────────
  "San Salvador, SV",
  "Santa Ana, SV",
  "San Miguel, SV",

  // ── Honduras ────────────────────────────────────────────
  "Tegucigalpa, HN",
  "San Pedro Sula, HN",
  "La Ceiba, HN",

  // ── Nicaragua ───────────────────────────────────────────
  "Managua, NI",
  "León, NI",
  "Granada, NI",

  // ── Costa Rica ──────────────────────────────────────────
  "San José, CR",
  "Alajuela, CR",
  "Limón, CR",
  "Liberia, CR",
  "Espíritu Santo, CR",

  // ── Panamá ──────────────────────────────────────────────
  "Ciudad de Panamá, PA",
  "Colón, PA",
  "David, PA",

  // ── Colombia ────────────────────────────────────────────
  "Bogotá, CO",
  "Medellín, CO",
  "Cali, CO",
  "Barranquilla, CO",
  "Cartagena, CO",
  "Cúcuta, CO",
  "Bucaramanga, CO",
  "Santa Marta, CO",
  "Pereira, CO",

  // ── Venezuela ───────────────────────────────────────────
  "Caracas, VE",
  "Maracaibo, VE",
  "Valencia, VE",
  "Barquisimeto, VE",
  "Maracay, VE",

  // ── Ecuador ─────────────────────────────────────────────
  "Quito, EC",
  "Guayaquil, EC",
  "Cuenca, EC",
  "Manta, EC",
  "Machala, EC",

  // ── Perú ────────────────────────────────────────────────
  "Lima, PE",
  "Callao, PE",
  "Arequipa, PE",
  "Trujillo, PE",
  "Chiclayo, PE",
  "Piura, PE",
  "Cusco, PE",

  // ── Bolivia ─────────────────────────────────────────────
  "La Paz, BO",
  "Santa Cruz de la Sierra, BO",
  "Cochabamba, BO",
  "El Alto, BO",

  // ── Chile ───────────────────────────────────────────────
  "Santiago, CL",
  "Valparaíso, CL",
  "Viña del Mar, CL",
  "Concepción, CL",
  "Antofagasta, CL",
  "Iquique, CL",

  // ── Argentina ───────────────────────────────────────────
  "Buenos Aires, AR",
  "Córdoba, AR",
  "Rosario, AR",
  "Mendoza, AR",
  "La Plata, AR",
  "Mar del Plata, AR",
  "Tucumán, AR",
  "Salta, AR",

  // ── Uruguay ─────────────────────────────────────────────
  "Montevideo, UY",
  "Salto, UY",
  "Paysandú, UY",

  // ── Paraguay ────────────────────────────────────────────
  "Asunción, PY",
  "Ciudad del Este, PY",
  "Encarnación, PY",

  // ── Brasil ──────────────────────────────────────────────
  "São Paulo, BR",
  "Rio de Janeiro, BR",
  "Brasília, BR",
  "Salvador, BR",
  "Fortaleza, BR",
  "Belo Horizonte, BR",
  "Curitiba, BR",
  "Porto Alegre, BR",
  "Recife, BR",
  "Manaus, BR",
  "Campinas, BR",
  "Santos, BR",

  // ── República Dominicana ────────────────────────────────
  "Santo Domingo, DO",
  "Santiago de los Caballeros, DO",
  "Punta Cana, DO",

  // ── Cuba ────────────────────────────────────────────────
  "La Habana, CU",
  "Santiago de Cuba, CU",

  // ── Puerto Rico ─────────────────────────────────────────
  "San Juan, PR",
  "Ponce, PR",

  // ── Japón ───────────────────────────────────────────────
  "Tokio, JP",
  "Yokohama, JP",
  "Inzai, JP",
  "Osaka, JP",
  "Nagoya, JP",
  "Kobe, JP",
  "Kioto, JP",
  "Fukuoka, JP",
  "Sapporo, JP",
];
