export const CIUDADES_MEXICO: string[] = [
  "Acapulco",
  "Acuña",
  "Aguascalientes",
  "Altamira",
  "Apodaca",
  "Bahía de Banderas",
  "Caborca",
  "Cabo San Lucas",
  "Campeche",
  "Cancún",
  "Cárdenas",
  "Celaya",
  "Chetumal",
  "Chihuahua",
  "Chilpancingo",
  "Ciudad Constitución",
  "Ciudad de México",
  "Ciudad del Carmen",
  "Ciudad Juárez",
  "Ciudad Obregón",
  "Ciudad Valles",
  "Ciudad Victoria",
  "Coatzacoalcos",
  "Colima",
  "Comitán",
  "Córdoba",
  "Cozumel",
  "Cuauhtémoc",
  "Cuautla",
  "Cuernavaca",
  "Culiacán",
  "Delicias",
  "Durango",
  "Ecatepec",
  "Ensenada",
  "Escobedo",
  "Fresnillo",
  "Gómez Palacio",
  "Guadalajara",
  "Guadalupe",
  "Guanajuato",
  "Guasave",
  "Guaymas",
  "Hermosillo",
  "Hidalgo del Parral",
  "Irapuato",
  "Juchitán",
  "La Paz",
  "Lagos de Moreno",
  "Lázaro Cárdenas",
  "León",
  "Lerdo",
  "Linares",
  "Loreto",
  "Los Cabos",
  "Los Mochis",
  "Manzanillo",
  "Matamoros",
  "Matehuala",
  "Mazatlán",
  "Mérida",
  "Mexicali",
  "Minatitlán",
  "Monclova",
  "Monterrey",
  "Morelia",
  "Navojoa",
  "Navolato",
  "Nezahualcóyotl",
  "Nogales",
  "Nuevo Casas Grandes",
  "Nuevo Laredo",
  "Oaxaca",
  "Orizaba",
  "Pachuca",
  "Piedras Negras",
  "Playa del Carmen",
  "Poza Rica",
  "Progreso",
  "Puebla",
  "Puerto Vallarta",
  "Querétaro",
  "Reynosa",
  "Rosarito",
  "Sabinas",
  "Salamanca",
  "Salina Cruz",
  "Saltillo",
  "San Cristóbal de las Casas",
  "San José del Cabo",
  "San Juan del Río",
  "San Luis Potosí",
  "San Luis Río Colorado",
  "San Miguel de Allende",
  "San Nicolás de los Garza",
  "San Pedro Garza García",
  "Santa Catarina",
  "Silao",
  "Tampico",
  "Tapachula",
  "Taxco",
  "Tecate",
  "Tecomán",
  "Tehuacán",
  "Tepic",
  "Texcoco",
  "Tijuana",
  "Tlalnepantla",
  "Tlaquepaque",
  "Tlaxcala",
  "Toluca",
  "Tonalá",
  "Torreón",
  "Tula",
  "Tulancingo",
  "Tulum",
  "Tuxtla Gutiérrez",
  "Tuxpan",
  "Uruapan",
  "Valladolid",
  "Veracruz",
  "Villahermosa",
  "Xalapa",
  "Zacatecas",
  "Zamora",
  "Zapopan",
  "Zihuatanejo",
];
